---
title: "Proportions"
author: "Me"
date: "3/22/2018"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
master = read.csv("outliers complete.csv")
```

```{r proportions}
master$mention.outliers

master$mention.outliers = factor(master$mention.outliers,
                      levels = c("no", "yes"),
                      labels = c("No", "Yes"))
table(master$mention.outliers)

#no
1688/2230 
#0.7569507

#yes
541/2230
#0.2426009
```

```{r reason}
master$reason.code

master$reason.code = factor(master$reason.code,
                      levels = c("", "did not follow instructions", "experimenter error", "experimenter error, statistical reasons", "no reason", "participant error", "participant error, experimenter error", "participant error, statisical reasons", "participant error, statistical reason", "participant error, statistical reasons", "statistical reason", "statistical reasons"),
                      labels = c("None", "Did Not Follow Instructions", "Experimenter Error", "Experimenter Error, Statistical Reasons", "No Reason", "Participant Error", "Participant Error, Experimenter Error", "Participant Error, Statisical Reasons", "Participant Error, Statistical Reason", "Participant Error, Statistical Reasons", "Statistical Reason", "Statistical Reasons"))

table(master$reason.code)
#None
1719/2231

#did not follow instructions
1/2231

#experimenter error(ee)
14/2231

#ee, statistical reason(sr)
1/2231

#noreason
5/2231

#participant error (pe)
317/2231

#pe,ee
15/2231

#pe,sr
6/2231

#pe,sr
1/2231

#pe,sr
26/2231

#sr
59/2231

#sr
67/2231

```

```{r Peopledata}
master$people.or.data.points
master$people.or.data.points = factor(master$people.or.data.points,
                      levels = c("", "both", "data points", "data points ", "none found", "people", "people "),
                      labels = c("None", "Both", "Data Points", "Data Points ", "None Found", "People", "People "))

table(master$people.or.data.points)

#none
1699/2231

#both
29/2231

#data points
115/2231

#data points
1/2231

#none found 
14/2231

#people
370/2231

#people
3/2231
```
```{r BasicsBayes}
master$Basics
table(master$Basics)
#master$Basics = factor(master$Basics,
                     # levels = c("0", "1"),
                      #labels = c("No", "Yes"))
#table(master$Basics)
#0
1317/2231
#1
914/2231

master$BayesOther
table(master$BayesOther)
#master$BayesOther = factor(master$BayesOther,
                      #levels = c("0", "1"),
                      #labels = c("No", "Yes"))
#table(master$BayesOther)
#0
2035/2231
#1
196/2231

```

```{r journalgraph}
library(ggplot2)

theme = theme(panel.grid.major = element_blank(), 
              panel.grid.minor = element_blank(), 
              panel.background = element_blank(), 
              axis.line = element_line(colour = "black"), 
              legend.key = element_rect(fill = "white"),
              text = element_text(size = 15))
 
bargraph = ggplot(master, aes(Type, , fill = time.pulled))
bargraph +
  stat_summary(fun.x = mean, 
               geom = "bar", 
               position="dodge") + 
  stat_summary(fun.data = mean_cl_normal, 
               geom = "errorbar", 
               position = position_dodge(width = 0.90), 
               width = 0.2) + 
  theme +
  xlab("Journal") +
  ylab("Proportion") + 
  coord_cartesian(ylim = c(0,1))+
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
```
```{r journalprop}
table(master$time.pulled)

#2012
1085/2231

#2017
1146/2231

library(MOTE)
#overall
d.prop(p1 = 0.486329, p2 = 0.513671, n1 = 1085, n2 = 1146, a = .05)
```

